### ISSUE TITLE
Superfluous Java Dependancy 

### ISSUE THREAD

**Issue by benwaine** [hoborglabs/ansible_gocd_server#2]
This module is dependant on `java` see `meta/main.yml`. 

``` yml

---

galaxy_info:
  author: "Wojtek Oledzki"
  description: "Install the Go Continuous Delivery server."
  license: MIT
  min_ansible_version: 1.8
  platforms:
    - name: Ubuntu
      versions:
        - all
  categories:
    - development

dependencies:
  - java
```

When attempting to run the play an error is displayed indicating the java module can not be found. Furthermore the apt package invoked by the play installs the open JDK. I'd remove this and update `defaults/main.yml` java_home variable to point to the open JDK (on ubuntu 14.04 `/usr/lib/jvm/java-7-openjdk-amd64/jre`)
